### ISSUE TITLE
Телеграм бот 

### ISSUE THREAD

**Issue by Ogurche** [pythontoday/weather_telegram_bot#1]
День добрый, Нам обязательно копировать код из файла main.py или мы можем в коде бота через импорт как-то вызвать функцию? 
Вопрос возможно глупый, но не очень хорошо понимаю пока.

**Comment by Ozodbekake** [comment]
Teligiraf

**Comment by Ozodbekake** [comment]
Serves

**Comment by Ozodbekake** [comment]
serves
